### ISSUE TITLE
[BUG反馈][致命][巫妖输不起把你存档崩了]

### ISSUE THREAD

**Issue by Fun-ways** [BiggestXuan/EMCWorld#14]
### BUG的表现:
暮色森林Boss巫妖进行传送时存档立即崩溃，返回界面显示“连接已丢失StackOverflowError”或“服务器已关闭”，有概率导致游戏存档无法进入（消失），重启游戏后恢复。会有小幅度的回档现象。
![屏幕截图_20230113_203618](https://user-images.githubusercontent.com/121800832/212324355-a5d9ad34-ee07-47b8-a6a4-b49f3b41bdb5.png)
![屏幕截图_20230113_203628](https://user-images.githubusercontent.com/121800832/212324346-671699b9-3ac1-4c79-a90c-4ca1a4974eb7.png)
### 复现方法:
巫妖，仇恨，等

### 操作环境:

- JAVA版本(jdk-11.0.15.1):
- EMC World 版本(0.4.0):

### 任何你觉得有必要补充的:
在另一个新存档测试时也出现了崩溃。测试存档均为单人模式。

**Comment by BiggestXuan** [comment]
记录下来：
java.lang.NullPointerException
at biggestxuan.emcworld.common.events.LivingEvent.LivingJoinWorldEvent.livingJoinWorldEvent(LivingJoinWorldEvent.java:37)
at net.minecraftforge.eventbus.ASMEventHandler_1600_LivingJoinWorldEvent_livingJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813)
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754)
	at twilightforest.entity.ai.LichShadowsGoal.spawnShadowClone(LichShadowsGoal.java:95)
	at twilightforest.entity.ai.LichShadowsGoal.checkAndSpawnClones(LichShadowsGoal.java:82)
	at twilightforest.entity.ai.LichShadowsGoal.func_75246_d(LichShadowsGoal.java:50)

预计下次更新修复~

**Comment by BiggestXuan** [comment]
0.4.0 - pre2 版本修复~
